spring:
  application:
    name: jutjubic

  datasource:
    url: jdbc:postgresql://localhost:5432/jutjubic
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  # Email konfiguracija
  mail:
    host: smtp.gmail.com
    port: 587
    username: jutjubicisa@gmail.com
    password: edqu lsoc jhaz cwde 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 210MB
  
  # DODAJ OVO - Timeout za async requeste
  mvc:
    async:
      request-timeout: 600000  # 10 minuta

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
  health:
    db:
      enabled: true

# JWT konfiguracija
jwt:
  secret: JutjubicSecretKeyForJWTTokenGenerationAndValidation2025IsaProjekat
  expiration: 86400  # 24 sata u sekundama

# App URLs
app:
  backend:
    url: https://astronautically-heathered-nestor.ngrok-free.dev

server:
  port: 8080
  connection-timeout: 600000  # 10 minuta
  tomcat:
    connection-timeout: 600000  # 10 minuta
    max-swallow-size: 250MB